spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5555/almoxarifado-homologacao}
    username: ${ALMOXARIFADO_DB_USER_HOMOLOGACAO}
    password: ${ALMOXARIFADO_DB_PASSWORD_HOMOLOGACAO}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: almoxarifado-pool-homologacao
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000
      leak-detection-threshold: 60000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
