networks:
  aratech-network:
    driver: bridge

volumes:
  almoxarifado-db-prod-data:
  login-db-prod-data:
  portaria-db-prod-data:
  recursoshumanos-db-prod-data:
  administracao-db-prod-data:

services:

  almoxarifado-db:
    image: postgres:17.4
    container_name: almoxarifado-db-prod
    restart: always
    ports:
      - "5575:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: almoxarifado-prod
    volumes:
      - almoxarifado-db-prod-data:/var/lib/postgresql/data
    networks:
      - aratech-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  login-db:
    image: postgres:17.4
    container_name: login-db-prod
    restart: always
    ports:
      - "5576:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: login-prod
    volumes:
      - login-db-prod-data:/var/lib/postgresql/data
    networks:
      - aratech-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  portaria-db:
    image: postgres:17.4
    container_name: portaria-db-prod
    restart: always
    ports:
      - "5577:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: portaria-prod
    volumes:
      - portaria-db-prod-data:/var/lib/postgresql/data
    networks:
      - aratech-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  recursoshumanos-db:
    image: postgres:17.4
    container_name: recursoshumanos-db-prod
    restart: always
    ports:
      - "5578:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recursoshumanos-prod
    volumes:
      - recursoshumanos-db-prod-data:/var/lib/postgresql/data
    networks:
      - aratech-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  administracao-db:
    image: postgres:17.4
    container_name: administracao-db-prod
    restart: always
    ports:
      - "5579:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: administracao-prod
    volumes:
      - administracao-db-prod-data:/var/lib/postgresql/data
    networks:
      - aratech-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.15
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - aratech-network

  kafka:
    image: confluentinc/cp-kafka:7.2.15
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - aratech-network

  almoxarifado:
    build: ./almoxarifado
    container_name: almoxarifado
    restart: always
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: producao
      SPRING_DATASOURCE_URL: jdbc:postgresql://almoxarifado-db:5432/almoxarifado-prod
      ALMOXARIFADO_DB_USER_PROD: postgres
      ALMOXARIFADO_DB_PASSWORD_PROD: postgres
    depends_on:
      almoxarifado-db:
        condition: service_healthy
    networks:
      - aratech-network

  login:
    build: ./login
    container_name: login
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: producao
      SPRING_DATASOURCE_URL: jdbc:postgresql://login-db:5432/login-prod
      LOGIN_DB_USER_PROD: postgres
      LOGIN_DB_PASSWORD_PROD: postgres
    depends_on:
      login-db:
        condition: service_healthy
    networks:
      - aratech-network

  portaria:
    build: ./portaria
    container_name: portaria
    restart: always
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: producao
      SPRING_DATASOURCE_URL: jdbc:postgresql://portaria-db:5432/portaria-prod
      PORTARIA_DB_USER_PROD: postgres
      PORTARIA_DB_PASSWORD_PROD: postgres
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      portaria-db:
        condition: service_healthy
    networks:
      - aratech-network

  recursoshumanos:
    build: ./recursoshumanos
    container_name: recursoshumanos
    restart: always
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: producao
      SPRING_DATASOURCE_URL: jdbc:postgresql://recursoshumanos-db:5432/recursoshumanos-prod
      RH_DB_USER_PROD: postgres
      RH_DB_PASSWORD_PROD: postgres
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      recursoshumanos-db:
        condition: service_healthy
    networks:
      - aratech-network

  administracao:
    build: ./administracao
    container_name: administracao
    restart: always
    ports:
      - "8084:8084"
    environment:
      SPRING_PROFILES_ACTIVE: producao
      SPRING_DATASOURCE_URL: jdbc:postgresql://administracao-db:5432/administracao-prod
      ADM_DB_USER_PROD: postgres
      ADM_DB_PASSWORD_PROD: postgres
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      administracao-db:
        condition: service_healthy
    networks:
      - aratech-network

  aratech-frontend:
    build: ./aratechFrontend/aratech-movies-frontend
    container_name: aratech-frontend
    restart: always
    ports:
      - "80:80"
    networks:
      - aratech-network
