server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /almoxarifado/ {
        proxy_pass http://almoxarifado:8081/almoxarifado/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
