export const PRODUTOS_ALMOXARIFADO_ROLES = [
  'ENCARREGADO_ALMOXARIFADO',
  'CONFERENTE_ALMOXARIFADO',
  'COMPRAS',
  'ENCARREGADO_PINTURA',
  'ENCARREGADO_EMBALAGEM',
  'ENCARREGADO_BORDA',
  'GERENTE_GERAL'
];
