spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${LOGIN_DB_USER_PROD}
    password: ${LOGIN_DB_PASSWORD_PROD}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: login-pool-prod
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000
      leak-detection-threshold: 60000

  mail:
    username: ${EMAIL}
    password: ${SENHA_EMAIL}
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: aratech-login
      auto-offset-reset: earliest

aratech:
  config:
    kafka:
      topics:
        login-funcionario: 'aratech.login-funcionario'

password:
  reset:
    link: http://aratech-frontend:80/reset-password?code=
  primeiro:
    acesso:
      link: http://localhost:80/primeiro-acesso?code=

jwt:
  chave-secreta: ${JWT_CHAVE_SECRETA}
  tempo-expiracao: ${JWT_TEMPO_EXPIRACAO}
