CREATE TABLE funcionarios (
    id                  BIGSERIAL     PRIMARY KEY,
    nome                VARCHAR(150)  NOT NULL,
    cpf                 VARCHAR(14)   NOT NULL UNIQUE,
    rg                  VARCHAR(12),
    pis                 VARCHAR(15),
    data_nascimento     DATE          NOT NULL,
    sexo                VARCHAR(1)    NOT NULL,
    estado_civil        VARCHAR(20),
    nome_mae            VARCHAR(150)  NOT NULL,
    nome_pai            VARCHAR(150),
    cep                 VARCHAR(9)    NOT NULL,
    logradouro          VARCHAR(200)  NOT NULL,
    numero              VARCHAR(10)   NOT NULL,
    complemento         VARCHAR(60),
    bairro              VARCHAR(100)  NOT NULL,
    cidade              VARCHAR(100)  NOT NULL,
    uf                  VARCHAR(2)    NOT NULL,
    telefone            VARCHAR(15),
    celular             VARCHAR(16),
    data_admissao       DATE          NOT NULL,
    tipo_contrato       VARCHAR(60)   NOT NULL,
    jornada_horas       INTEGER       CHECK (jornada_horas BETWEEN 1 AND 60),
    cargo               VARCHAR(100)  NOT NULL,
    tipo_funcionario    VARCHAR(30)   NOT NULL,
    setor               VARCHAR(100)  NOT NULL,
    salario             NUMERIC(12,2) NOT NULL CHECK (salario > 0),
    email               VARCHAR(150)  NOT NULL UNIQUE,
    banco               VARCHAR(100)  NOT NULL,
    agencia             VARCHAR(10)   NOT NULL,
    conta               VARCHAR(20)   NOT NULL,
    tipo_conta          VARCHAR(10)   NOT NULL CHECK (tipo_conta IN ('corrente', 'poupanca')),
    pix                 VARCHAR(100),
    ativo               BOOLEAN       NOT NULL DEFAULT TRUE,
    email_corporativo   VARCHAR(255),
    password            VARCHAR(255)
);
